#ifndef __COMMUNICATION_SOCKET_H__
#define __COMMUNICATION_SOCKET_H__

#define BUFFER_LENGTH 2048
#define BOUNDARY_LENGTH 128

#define MAX_SOCKETS_CONNECTIONS 5

#define NO_COMM_ERROR 0

#define ERR_SOCKET_NOT_CREATED 3100
#define ERR_SOCKET_NOT_BINDED 3101
#define ERR_SOCKET_NOT_LISTENED 3102
#define ERR_SOCKET_NOT_ACCEPTED 3103
#define ERR_SOCKET_ADDRESS_NOT_CREATED 3104

#endif
