#ifndef __COMMUNICATION_FIFO_H__
#define __COMMUNICATION_FIFO_H__

#define BUFFER_LENGTH 2048
#define BOUNDARY_LENGTH 128

#define FIFO_PATH_PREFIX "/tmp/"
#define FIFO_REQUEST_EXTENSION ".req"
#define FIFO_RESPONSE_EXTENSION ".res"
#define FIFO_EXTENSION ".fifo"
#define FIFO_INPUT_EXTENSION ".in"
#define FIFO_PERMS 0666

#define NO_COMM_ERROR 0

#define ERR_FIFO_NOT_CREATED 3000
#define ERR_FIFO_CANT_OPEN_CONNECTION_FILE 3001
#define ERR_FIFO_INVALID_ADDRESS 3002
#define ERR_FIFO_REQUEST_CANT_CREATE 3003
#define ERR_FIFO_RESPONSE_CANT_OPEN 3004
#define ERR_FIFO_REQUEST_CANT_OPEN 3005
#define ERR_FIFO_AUTHENTICATION_FAIL 3006

#endif
