#ifndef __COMMUNICATION_H__
#define __COMMUNICATION_H__

#include <comm.addr.api.h>
#include <comm.connection.api.h>
#include <comm.send.api.h>
#include <comm.receive.api.h>

#define BUFFER_LENGTH 2048
#define BOUNDARY_LENGTH 128

#define MAX_SOCKETS_CONNECTIONS 5

#define NO_COMM_ERROR 0

#define ERR_FIFO_NOT_CREATED 				3000
#define ERR_FIFO_CANT_OPEN_CONNECTION_FILE 	3001
#define ERR_FIFO_INVALID_ADDRESS 			3002
#define ERR_FIFO_REQUEST_CANT_CREATE 		3003
#define ERR_FIFO_RESPONSE_CANT_OPEN 		3004
#define ERR_FIFO_REQUEST_CANT_OPEN 			3005
#define ERR_FIFO_AUTHENTICATION_FAIL 		3006

#define ERR_SOCKET_NOT_CREATED				3100
#define ERR_SOCKET_NOT_BINDED				3101
#define ERR_SOCKET_NOT_LISTENED				3102
#define ERR_SOCKET_NOT_ACCEPTED				3103
#define ERR_SOCKET_ADDRESS_NOT_CREATED		3104

#endif